{% set name = "notolog" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/notolog-{{ version }}.tar.gz
  sha256: dc4200ad93dbcf19eef0a7e579358b5023309c2e03da74754f2c5fcd7146cd2e

build:
  entry_points:
    - notolog=notolog.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<=3.13
    - pip
    - poetry-core >=1.5.0
  run:
    - python >=3.9,<=3.13
    - cffi >=1.17.1
    - click >=8.1.7
    - cryptography >=42.0.7
    - emoji >=2.14.0
    - iniconfig >=2.0.0
    - Markdown >=3.6
    - packaging >=24.0
    - pluggy >=1.5.0
    - pycparser >=2.22
    - Pygments >=2.18.0
    - PySide6 >=6.7.0
    - qasync >=0.27.1
    - tomli >=2.0.1
    - tomli-w >=1.0.0
    - typing_extensions >=4.11.0
    - llama-cpp-python >=0.2.24

test:
  imports:
    - notolog
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-mock
    - pyside6
  source_files:
    - tests
  commands:
    - pytest tests/test_pkg_integration.py
    # Package requirements on PyPI differ slightly from those on conda-forge.
    #- pip check

about:
  home: https://notolog.app
  summary: Notolog - Python Markdown Editor
  description: |
    Notolog is an open-source Markdown editor licensed under MIT, featuring a simple interface, advanced tools, and an AI assistant, built with Python and PySide6.
  dev_url: https://github.com/notolog/notolog-editor/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - notolog
