{% set name = "notolog" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/notolog-{{ version }}.tar.gz
  sha256: 35289a15e48dd3ca5b0e96a9ec31075a35a1d767ec05af879db8ff1719956e04

build:
  entry_points:
    - notolog=notolog.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - pip
    - poetry-core >=1.5.0
  run:
    - python >=3.9,<4.0
    - cffi >=1.16.0
    - click >=8.1.7
    - cryptography >=42.0.7
    - emoji >=2.12.1
    - iniconfig >=2.0.0
    - Markdown >=3.6
    - packaging >=24.0
    - pluggy >=1.5.0
    - pycparser >=2.22
    - Pygments >=2.18.0
    - PySide6 >=6.7.0
    - qasync >=0.27.1
    - tomli >=2.0.1
    - tomli-w >=1.0.0
    - typing_extensions >=4.11.0

test:
  imports:
    - notolog
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-mock
    - pyside6
  source_files:
    - tests
  commands:
    - pytest tests/test_pkg_integration.py
    # Package requirements on PyPI differ slightly from those on conda-forge.
    #- pip check

about:
  home: https://github.com/notolog/notolog-editor
  summary: Notolog - Python Markdown Editor
  description: |
    Notolog is an open-source Python Markdown editor that blends simplicity with functionality. Designed with PySide6, it helps tackle daily programming challenges and enhance Python proficiency.
  dev_url: https://github.com/notolog/notolog-editor/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - notolog
